spring:
    application:
        name: Config-Default
    datasource:
        url: jdbc:mysql://localhost:3306/userservices
        username: root
        password: root123
        driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-withieureka: true
        service-url:
            default-zone: hhtp://localhost:8761/eureka
