spring:
    application:
        name: Config-Default

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-withieureka: true
        service-url:
            default-zone: hhtp://localhost:8761/eureka
    
